import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero/Hero";
import Scheduler from "../components/Scheduler/Scheduler";
import Header from "../components/Layouts/header/Header";
import Layout from "../components/Layouts/Layout/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        children={
          <>
            <Hero />
            <Scheduler />
          </>
        }
      />
    </div>
  );
}
