import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero/Hero";
import Scheduler from "../components/Scheduler/Scheduler";
import Header from "../components/shared/header/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-gradient-to-b from-pink-100 ">
        <Header />
        <Hero />
        <Scheduler />
      </main>
    </div>
  );
}
